### ISSUE TITLE
Not seeing any icons

### ISSUE THREAD

**Issue by MrMattTaylor** [rhythmagency/rhythm.umbraco7.font-awesome-icon-picker#7]
I've literally followed the instructions and copied the FontAwesomeIconPicker folder into App_Pluggins, created a datatype, assigned it to a property and used it on my documenttype.

I can see the dropdown with the font names but no icons.
I'm using Umbraco 7.2.1.

**Comment by MrMattTaylor** [comment]
There's no search functionality either.

**Comment by Nicholas-Westby** [comment]
Thanks for the report. Which version are you using? I just fixed a bug 8 days ago in which icons were not displaying: https://github.com/rhythmagency/rhythm.umbraco7.font-awesome-icon-picker/commit/111aec61fb8105dfdc72903b0eb3cf3fc8fb0350

**Comment by Nicholas-Westby** [comment]
FYI, the icons appear for me and the search works for me:

![icon-picker](https://cloud.githubusercontent.com/assets/5933222/5631613/b1f3072e-957c-11e4-90e0-1de769dfd8a5.gif)

Perhaps try the latest version, making sure to delete your App\_Data/TEMP folders, clearing your browser cache, and recycling your app pool.

**Comment by MrMattTaylor** [comment]
I was using the version that I downloaded here today.

I ripped it all out, deleted the App_Data/TEMP folders and then put it all back in again.
Still the same problem until I Ctrl+F5 the browser. Then is started working.

A bit strange but thanks.

Matt
